services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Bigproject_app
    restart: unless-stopped
    working_dir: /var/www/symfony
    volumes:
      - ./symfony:/var/www/symfony
    networks:
      - symfony_network

  # Nginx Service
  nginx:
    image: nginx:1.24-alpine
    container_name: Bigproject_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/symfony
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - symfony_network

  # MySQL Service
  db:
    image: mysql:8.2.0
    container_name: Bigproject_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Bigproject
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_PASSWORD: your_password
      MYSQL_USER: symfony_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - symfony_network

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: Bigproject_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
      PMA_USER: symfony_user
      PMA_PASSWORD: your_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  dbdata: 